### ISSUE TITLE
[Bug] If there are two independent quantum registers in Qiskit, conversion to Quasar fails

### ISSUE THREAD

**Issue by stephendiadamo** [qcware/qusetta#7]
If I generate the circuit below, Qusetta will throw an error regarding the uniqueness of the qubit index -- it tries to CNOT a qubit with itself. 

```
aux = QuantumRegister(1, 'aux')
num_reg = 10
q_reg = QuantumRegister(num_reg, 'q')
c_reg = ClassicalRegister(1, 'c_reg')
qc = QuantumCircuit(aux, q_reg, c_reg)
qc.cnot(aux[0], q_reg[0])
```

The expectation is that it can detect that the registers are different and properly convert the circuit.

**Comment by jtiosue** [comment]
Indeed, qusetta only works within one register at a time. At the moment, there are no plans to extend the functionality of qusetta with regard to this functionality. I would suggest that you take a look at [qcware_transpile](https://github.com/qcware/qcware_transpile) (i.e. qusetta++), a project that @vputz has been working on.
